controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

live_component:
    resource: '@LiveComponentBundle/Resources/config/routing/live_component.xml'